' Auto-generated by workspace_admin/scripts/generate-task-wrappers.py - DO NOT EDIT BY HAND.
' Task: HealthAssistantDailySync. Hidden launcher (window style 0) + result capture (P0 upgrade 2026-07-25).
' Writes D:\AIWorkspace\workspace_admin\state\task-results\HealthAssistantDailySync.json and exits with the wrapped command's exit code.
Option Explicit
Const TASK_NAME = "HealthAssistantDailySync"
Const EXPECT_OUTPUT = 0
Const ASYNC_LAUNCH = 0
Dim shell, fso, stateDir, resDir, logDir, logFile, cmd, exitCode, logSize, suspicious, ts, json, outFile, Q
Q = Chr(34)
Set shell = CreateObject("WScript.Shell")
Set fso = CreateObject("Scripting.FileSystemObject")
stateDir = "D:\AIWorkspace\workspace_admin\state"
resDir = stateDir & "\task-results"
logDir = stateDir & "\logs"
If Not fso.FolderExists(resDir) Then fso.CreateFolder(resDir)
If Not fso.FolderExists(logDir) Then fso.CreateFolder(logDir)
logFile = logDir & "\" & TASK_NAME & ".last.log"
shell.CurrentDirectory = "D:\AIWorkspace\projects\health_assistant"
cmd = "cmd.exe /c C:\Python314\pythonw.exe ""D:\AIWorkspace\projects\health_assistant\scripts\daily_sync.py"" > " & Q & logFile & Q & " 2>&1"
If ASYNC_LAUNCH = 1 Then
    shell.Run cmd, 0, False
    exitCode = 0
Else
    exitCode = shell.Run(cmd, 0, True)
End If

logSize = 0
If fso.FileExists(logFile) Then logSize = fso.GetFile(logFile).Size
suspicious = "false"
If ASYNC_LAUNCH = 0 And exitCode = 0 And EXPECT_OUTPUT = 1 And logSize = 0 Then suspicious = "true"
ts = Year(Now) & "-" & Right("0" & Month(Now), 2) & "-" & Right("0" & Day(Now), 2) & "T" & Right("0" & Hour(Now), 2) & ":" & Right("0" & Minute(Now), 2) & ":" & Right("0" & Second(Now), 2)
json = "{" & Q & "task" & Q & ":" & Q & "HealthAssistantDailySync" & Q & "," & Q & "finished_at" & Q & ":" & Q & ts & Q & "," & Q & "exit_code" & Q & ":" & exitCode & "," & Q & "async_launch" & Q & ":" & LCase(CStr(ASYNC_LAUNCH = 1)) & "," & Q & "console_log" & Q & ":" & Q & Replace(logFile, "\", "\\") & Q & "," & Q & "console_bytes" & Q & ":" & logSize & "," & Q & "suspicious_zero_output" & Q & ":" & suspicious & "}"
Set outFile = fso.CreateTextFile(resDir & "\" & TASK_NAME & ".json", True, False)
outFile.Write json
outFile.Close
If ASYNC_LAUNCH = 1 Then
    WScript.Quit 0
Else
    WScript.Quit exitCode
End If
